### ISSUE TITLE
Many chrome browsers start

### ISSUE THREAD

**Issue by kbullaughey** [testem/testem#1063] opened 2017-01-27 15:26 UTC
I'm using testem with and ember-cli project in dev mode launching Chrome. 

When I'm pausing at breakpoints to debug and saving files as I fix things, testem will launch new instances of Chrome. Before long I'll have five instances of Chrome running, all running my tests and slowing down my machine and hogging my CPU. Is this expected behavior or have I configured something wrong? or is it a bug. I'm happy to poke around, but I'm not sure where I would begin.

**Comment by johanneswuerbach** [comment] 2017-01-27 15:38
Sounds like a bug, testem expects the browser to connect to the testem server once its launched, maybe the breakpoint also breaks the websocket connection?

https://github.com/testem/testem/blob/master/lib/runners/browser_test_runner.js#L69

**Comment by justinaray** [comment] 2017-01-27 15:45
I am experiencing the same problem.  It started yesterday with breakpoints as @kbullaughey mentioned; however, I'm seeing it today with no breakpoints.  Anything else I can help with on a recreate?

Testem terminal shows `PhantomJS`, `Chrome`, `Chrome 55.0`, `Chrome 55.0`, ... `Chrome 55.0`

macOS Sierra
ember/ember-cli: 2.9.x
testem: 1.14.3

**Comment by justinaray** [comment] 2017-01-27 16:11
I upgraded chrome and rolled back to lts node and things seem to be better.  Not sure which was the culprit, but I'm assuming it was latest node?  Not using breakpoints currently, so that may still be an issue.

HTH

Chrome: 56.0.2924.76
Node: 6.9.4

**Comment by kbullaughey** [comment] 2017-01-28 16:10
I am using:

Chrome: 55.0.2883.95
Node: v4.5.0
Testem: 1.14.2
ember-cli: 2.10.0

**Comment by justinaray** [comment] 2017-02-07 20:17
I spoke too soon.  This still appears to be a problem without breakpoints.

**Comment by mfeckie** [comment] 2017-02-09 04:50
Similar issue here.  I see it if I set any filters on the tests or do anything with breakpoints.

**Comment by bendemboski** [comment] 2017-02-09 05:44
#1071 may be a fix for this issue. However, I haven't been able to repro this exact issue in any of my ember-cli projects. However, I do have a theory. Does anybody that hit this issue have `src_files` configured in your testem config? Can anybody that is able to repro this try running against the #1071 branch and see if it fixes the issue?

Here's my theory as to how #1071 might fix this bug. What #1071 is addressing is that if you do anything that causes the page to refresh (such as change your QUnit filters, or change some code to trigger ember-cli's live reloading), testem will create a new runner/reporter pair, so now there are two runners for the single browser instance. Then, if something causes testem to restart (such as one of the watched `src_files` changing), there are two runners, so the original browser would get killed and two browsers would get re-launched instead of just one.

**Closed** 2017-02-10 08:31 UTC

**Comment by Subtletree** [comment] 2018-08-02 23:13
I've had this happening for a while but haven't looked for a solution until now.

Think I've managed to reliably reproduce it:

- Add `debugger` to code
- `ember test --server`
- Open chrome inspector in test window
- Once code hits the breakpoint, **wait for 30 seconds** and then change a file and save.

A seconds window should open and leave the first window paused on the breakpoint.

Hard to track down as when you're looking for the error you're not waiting very long, stepping through code etc as if you're debugging something. When I left it for 15 seconds a second window did not open.

It also happens if you have left a breakpoint paused for 30 seconds or longer, then proceed to finish the tests and then change and save a file. It seems like the server disconnects from the client if it doesn't hear from the client for more than 20 seconds or so because its been paused on a breakpoint.

Have experienced on 2.8.2 and 2.9.1 but probably many versions before that too.

```
// testem.js
module.exports = {
  test_page: 'tests/index.html?hidepassed',
  disable_watching: true,
  launch_in_ci: [
    'Chrome'
  ],
  launch_in_dev: [
    'Chrome'
  ],
  browser_args: {
    Chrome: {
      ci: [
        // --no-sandbox is needed when running Chrome inside a container
        process.env.CI ? '--no-sandbox' : null,
        '--headless',
        '--disable-gpu',
        '--disable-dev-shm-usage',
        '--disable-software-rasterizer',
        '--mute-audio',
        '--remote-debugging-port=0',
        '--window-size=1440,900'
      ].filter(Boolean)
    }
  }
};
```
