### ISSUE TITLE
"on_start" times out on Mac OSX node v5 (works with node v6 and node v7)

### ISSUE THREAD

**Issue by reeteshranjan** [testem/testem#1142] opened 2017-06-18 08:23 UTC
I am building a testing tool in which testem is integrated. I have OSX/Windows/Ubuntu CI builds setup using Travis/Appveyor/CircleCI respectively. For each of these, I am having a matrix to support node v4 to node v7.

For OSX node 5, my test where there is an "on_start" hook, fails as testem never reads the expected text and times out. However; the same test works with node 6 and node 7.

I looked into the Process class and how onStdOut method is used for implementing this, and can't find what is wrong there. I wrote a simple execFile based test to see if it's a problem with node 5 that stdout is not pushed out for some reason. This test worked as it was able to get the stdout as expected.

Please let me know what more data you may need.

**Comment by johanneswuerbach** [comment] 2017-06-18 11:09
Could you share that test case? Also node 5 is no longer supported and only 4/6/(7)/8 should be used.

https://github.com/nodejs/LTS/blob/master/schedule.png

**Comment by stefanpenner** [comment] 2018-06-02 03:15
As node 5 is no longer supported, and the issue is resolved on node 6+, I am going to close this.

**Closed by stefanpenner** 2018-06-02 03:15 UTC
