### ISSUE TITLE
Cannot run against deployed application

### ISSUE THREAD

**Issue by pixelpax** [testem/testem#1206] opened 2018-01-19 22:20 UTC
Is there a way for testem to access remote urls and run tests against a deployed app? 

I can't find this info anywhere. It seems that `visit` does not execute an http request, but rather just manipulates the ember SPA router somehow. Is there a way I could get tests to render inside of an iframe perhaps? Or get visit get the site itself? This seems necessary in order to most accurately and safely test a product staged for deployment

**Comment by stefanpenner** [comment] 2018-06-02 03:10
This isn't currently a supported feature. It doesn't seem like an unreasonable feature to add, but sounds like it requires some design and thought to execute correctly.

I am marking this as a feature for future readers, but closing as it is not a bug. Although closed, discussions can still continue here.

**Closed by stefanpenner** 2018-06-02 03:10 UTC
