### ISSUE TITLE
Unhandled 'error' event when running testem ci in windows.

### ISSUE THREAD

**Issue by tircnf** [testem/testem#359] opened 2014-04-07 14:41 UTC
I've been running into a problem with trying to run testem ci under windows with phantomjs.

node --version
 v0.10.26

phantomjs --version
1.9.7

testem --version
0.6.14

to recreate.

```
npm install -g testem
npm install -g phantomjs
mkdir testem
cd testem
```
--create a spec.js file.
```

function hello() {return "hello";}

describe('hello', function(){
  it('should say hello', function(){
      expect(hello()).toBe('hello');
   });
});
```

make sure we have launchers defined.

testem launchers
```
info Seeking for config file...
Have 3 launchers available; auto-launch info displayed on the right.

Launcher      Type          CI  Dev
------------  ------------  --  ---
IE            browser       x
Chrome        browser       x
PhantomJS     browser       x
```

run the tests in ci mode.

The test runs properly in IE and Chrome, but an error is thrown when trying to use PhantomJS.

testem ci
```
ok 1 IE 9.0 - hello should say hello.
ok 2 Chrome 33.0 - hello should say hello.

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)    ...


```

If I cause PhatomJS to be run in dev mode, testem will hang, and I have to kill it with the task manager.

This happens on windows vista as well as windows 7.
it also happens under cygwin as well as a plain command prompt.
I ran into this by trying to run the ci task from lineman.

 
My workaround in my dev environment is to set launch_in_ci to only run Chrome.

**Comment by joeyespo** [comment] 2015-02-24 23:28
Just ran into this too.

Looks like the testem/lib/launcher.js error,

```bash
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)    ...
```

is related to `spawn` not running `phantomjs.bat` when installed with npm. What's worse is, `spawn` isn't even *able* to run `.bat` files. (See https://github.com/joyent/node/issues/2318)

I can confirm that [downloading](http://phantomjs.org/download.html) PhantomJS will work around this issue until either testem uses something like [node-cross-spawn](https://github.com/IndigoUnited/node-cross-spawn), or Node adds something like `spawnShell` as @isaacs [suggested](https://github.com/joyent/node/issues/2318#issuecomment-7462307).

**Comment by johanneswuerbach** [comment] 2015-12-28 22:16
This is fixed in testem master now.

**Closed** 2015-12-28 22:16 UTC
Labels: bug
